#!/bin/bash
SERVICE1=lce_queryd;
SERVICE2=lce_report_proxyd;
SERVICE3=lced;
SERVICE4=lce_tasld;
SERVICE5=lce_wwwd;
SERVICE6=postgresql;

if ps ax | grep -v grep | grep $SERVICE1 > /dev/null
then
    echo "$SERVICE1 service running, everything is fine"
else
    echo "$SERVICE1 is not running"
    echo "$SERVICE1 is not running!" | mail -s "Please check the $SERVICE1 process on the LCE Server (plislce1)" -r "LCE Process Monitor<noreply@azdor.gov>" RLudders@azdor.gov Infor
mationSecurityTeam@mydomain.com
fi

if ps ax | grep -v grep | grep $SERVICE2 > /dev/null
then
    echo "$SERVICE2 service running, everything is fine"
else
    echo "$SERVICE2 is not running"
    echo "$SERVICE2 is not running!" | mail -s "Please check the $SERVICE2 process on the LCE Server (plislce1)" -r "LCE Process Monitor<noreply@azdor.gov>" RLudders@azdor.gov Infor
mationSecurityTeam@mydomain.com
fi

if ps ax | grep -v grep | grep $SERVICE3 > /dev/null
then
    echo "$SERVICE3 service running, everything is fine"
else
    echo "$SERVICE3 is not running"
    echo "$SERVICE3 is not running!" | mail -s "Please check the $SERVICE3 process on the LCE Server (plislce1)" -r "LCE Process Monitor<noreply@azdor.gov>" RLudders@azdor.gov Infor
mationSecurityTeam@mydomain.com
fi

if ps ax | grep -v grep | grep $SERVICE4 > /dev/null
then
    echo "$SERVICE4 service running, everything is fine"
else
    echo "$SERVICE4 is not running"
    echo "$SERVICE4 is not running!" | mail -s "Please check the $SERVICE4 process on the LCE Server (plislce1)" -r "LCE Process Monitor<noreply@azdor.gov>" RLudders@azdor.gov Infor
mationSecurityTeam@mydomain.com
fi

if ps ax | grep -v grep | grep $SERVICE5 > /dev/null
then
    echo "$SERVICE5 service running, everything is fine"
else
    echo "$SERVICE5 is not running"
    echo "$SERVICE5 is not running!" | mail -s "Please check the $SERVICE5 process on the LCE Server (plislce1)" -r "LCE Process Monitor<noreply@azdor.gov>" RLudders@azdor.gov Infor
mationSecurityTeam@mydomain.com
fi

if ps ax | grep -v grep | grep $SERVICE6 > /dev/null
then
    echo "$SERVICE6 service running, everything is fine"
else
    echo "$SERVICE6 is not running"
    echo "$SERVICE6 is not running!" | mail -s "Please check the $SERVICE6 process on the LCE Server (plislce1)" -r "LCE Process Monitor<noreply@azdor.gov>" RLudders@azdor.gov Infor
mationSecurityTeam@mydomain.com
fi
